//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HimbeertoniRaidTool.Plugin.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CoreLocalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoreLocalization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HimbeertoniRaidTool.Plugin.Localization.CoreLocalization", typeof(CoreLocalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show help.
        /// </summary>
        internal static string Command_hrt {
            get {
                return ResourceManager.GetString("Command_hrt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prints usage information to chat.
        /// </summary>
        internal static string command_hrt_help {
            get {
                return ResourceManager.GetString("command_hrt_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the Configuration window.
        /// </summary>
        internal static string command_hrt_options {
            get {
                return ResourceManager.GetString("command:hrt:options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Welcome Window with explanations on how to use.
        /// </summary>
        internal static string command_hrt_welcome {
            get {
                return ResourceManager.GetString("command:hrt:welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        internal static string Config_Appearance {
            get {
                return ResourceManager.GetString("Config_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update interval (days).
        /// </summary>
        internal static string ConfigUi_BisUpdateInterval {
            get {
                return ResourceManager.GetString("ConfigUi_BisUpdateInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changelog Options.
        /// </summary>
        internal static string ConfigUi_Changelog_Title {
            get {
                return ResourceManager.GetString("ConfigUi_Changelog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update gear when examining.
        /// </summary>
        internal static string ConfigUi_checkbox_examine {
            get {
                return ResourceManager.GetString("ConfigUi_checkbox_examine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide in combat.
        /// </summary>
        internal static string ConfigUi_checkbox_hideInCombat {
            get {
                return ResourceManager.GetString("ConfigUi_checkbox_hideInCombat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hides all windows while character is in combat.
        /// </summary>
        internal static string ConfigUi_checkbox_hideInCombat_tooltip {
            get {
                return ResourceManager.GetString("ConfigUi_checkbox_hideInCombat_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically update own data.
        /// </summary>
        internal static string ConfigUi_checkbox_ownData {
            get {
                return ResourceManager.GetString("ConfigUi_checkbox_ownData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keeps gear and classes of logged in character up to date.
        /// </summary>
        internal static string ConfigUi_checkbox_ownData_tooltip {
            get {
                return ResourceManager.GetString("ConfigUi_checkbox_ownData_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save periodically.
        /// </summary>
        internal static string ConfigUi_checkbox_savePeriodically {
            get {
                return ResourceManager.GetString("ConfigUi_checkbox_savePeriodically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saves all data of this plugin periodically. (Helps prevent losing data if your game
        ///            crashes)
        ///        .
        /// </summary>
        internal static string ConfigUi_checkbox_savePeriodically_tooltip {
            get {
                return ResourceManager.GetString("ConfigUi_checkbox_savePeriodically_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update combat jobs.
        /// </summary>
        internal static string ConfigUi_checkbox_updateCombatJobs {
            get {
                return ResourceManager.GetString("ConfigUi_checkbox_updateCombatJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update disciple of hand jobs.
        /// </summary>
        internal static string ConfigUi_checkbox_updateDohJobs {
            get {
                return ResourceManager.GetString("ConfigUi_checkbox_updateDohJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update disciple of land jobs.
        /// </summary>
        internal static string ConfigUi_checkbox_updateDolJobs {
            get {
                return ResourceManager.GetString("ConfigUi_checkbox_updateDolJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etro Gear Updates.
        /// </summary>
        internal static string ConfigUi_EtroGearUpdates {
            get {
                return ResourceManager.GetString("ConfigUi_EtroGearUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Save.
        /// </summary>
        internal static string ConfigUi_heading_AutoSave {
            get {
                return ResourceManager.GetString("ConfigUi_heading_AutoSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic data update.
        /// </summary>
        internal static string ConfigUi_Heading_dataUpdate {
            get {
                return ResourceManager.GetString("ConfigUi_Heading_dataUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Interface.
        /// </summary>
        internal static string ConfigUi_heading_ui {
            get {
                return ResourceManager.GetString("ConfigUi_heading_ui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoSave interval (min).
        /// </summary>
        internal static string ConfigUi_input_AutoSaveInterval {
            get {
                return ResourceManager.GetString("ConfigUi_input_AutoSaveInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job specific config (affects all options above).
        /// </summary>
        internal static string ConfigUi_text_dataUpdateJobs {
            get {
                return ResourceManager.GetString("ConfigUi_text_dataUpdateJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update sets from etro.gg periodically.
        /// </summary>
        internal static string ConfigUi_UpdateBisOnStartUp {
            get {
                return ResourceManager.GetString("ConfigUi_UpdateBisOnStartUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data failed to save.
        /// </summary>
        internal static string Core_PeriodicSaveFailed {
            get {
                return ResourceManager.GetString("Core:PeriodicSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Saved successfully.
        /// </summary>
        internal static string Core_PeriodicSaveSuccessful {
            get {
                return ResourceManager.GetString("Core:PeriodicSaveSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string CoreConfig_Title {
            get {
                return ResourceManager.GetString("CoreConfig_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data failed to save.
        /// </summary>
        internal static string PeriodicSaveFailed {
            get {
                return ResourceManager.GetString("PeriodicSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Saved successfully.
        /// </summary>
        internal static string PeriodicSaveSuccessful {
            get {
                return ResourceManager.GetString("PeriodicSaveSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open LootMaster.
        /// </summary>
        internal static string WelcomeWindow_button_OpenLootMaster {
            get {
                return ResourceManager.GetString("WelcomeWindow_button_OpenLootMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open LootMaster main window (/lootmaster).
        /// </summary>
        internal static string WelcomeWindow_button_OpenLootMaster_tooltip {
            get {
                return ResourceManager.GetString("WelcomeWindow_button_OpenLootMaster_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Options.
        /// </summary>
        internal static string WelcomeWindow_button_OpenOptions {
            get {
                return ResourceManager.GetString("WelcomeWindow_button_OpenOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show configuration options (/hrt config).
        /// </summary>
        internal static string WelcomeWindow_button_OpenOptions_tooltip {
            get {
                return ResourceManager.GetString("WelcomeWindow_button_OpenOptions_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Himbeertoni Raid Tool.
        /// </summary>
        internal static string WelcomeWindow_Title {
            get {
                return ResourceManager.GetString("WelcomeWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Himbeertoni Raid Tool. Your companion in managing your raid group..
        /// </summary>
        internal static string WelcomeWindowLine1 {
            get {
                return ResourceManager.GetString("WelcomeWindowLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start your journey by opening LootMaster by typing &quot;/lootmaster&quot; (or &quot;/lm&quot;) in chat
        ///            (or the button below). There we already added your character for you.
        ///        .
        /// </summary>
        internal static string WelcomeWindowLine2 {
            get {
                return ResourceManager.GetString("WelcomeWindowLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next you can get your current gear either by using the &quot;magnifying glass&quot; button or
        ///            by examining your character via right clicking.
        ///        .
        /// </summary>
        internal static string WelcomeWindowLine3 {
            get {
                return ResourceManager.GetString("WelcomeWindowLine3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plugin will always update the gear for characters that were added to a group or
        ///            solo tab when examining the character in-game.
        ///        .
        /// </summary>
        internal static string WelcomeWindowLine4 {
            get {
                return ResourceManager.GetString("WelcomeWindowLine4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To really start using this you&apos;d need to add your group via the &quot;+ button&quot; right to
        ///            the Solo tab. For this you have two possibilities. &quot;From scratch&quot; let&apos;s you input
        ///            everything yourself like a noob. Or you can gather your group into a party (or wait for
        ///            the next gathering) and let the plugin do most of the work by choosing &quot;From current
        ///            group&quot;. You still have to give the group a name and maybe adjust nicknames for your
        ///            players.
        ///        .
        /// </summary>
        internal static string WelcomeWindowLine5 {
            get {
                return ResourceManager.GetString("WelcomeWindowLine5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you for example want the loot master to open on start, I would suggest you take a
        ///            quick look at the options. And go to the wiki for more detailed instructions :)
        ///        .
        /// </summary>
        internal static string WelcomeWindowLine6 {
            get {
                return ResourceManager.GetString("WelcomeWindowLine6", resourceCulture);
            }
        }
    }
}
