//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HimbeertoniRaidTool.Plugin.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CoreLoc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoreLoc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HimbeertoniRaidTool.Plugin.Localization.CoreLoc", typeof(CoreLoc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BiS.
        /// </summary>
        internal static string ChangelogCategory_BiS {
            get {
                return ResourceManager.GetString("ChangelogCategory_BiS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bugfix.
        /// </summary>
        internal static string ChangelogCategory_Bugfix {
            get {
                return ResourceManager.GetString("ChangelogCategory_Bugfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string ChangelogCategory_Configuration {
            get {
                return ResourceManager.GetString("ChangelogCategory_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gear.
        /// </summary>
        internal static string ChangelogCategory_Gear {
            get {
                return ResourceManager.GetString("ChangelogCategory_Gear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string ChangelogCategory_General {
            get {
                return ResourceManager.GetString("ChangelogCategory_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localization.
        /// </summary>
        internal static string ChangelogCategory_Localization {
            get {
                return ResourceManager.GetString("ChangelogCategory_Localization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loot Master.
        /// </summary>
        internal static string ChangelogCategory_LootMaster {
            get {
                return ResourceManager.GetString("ChangelogCategory_LootMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loot Session.
        /// </summary>
        internal static string ChangelogCategory_LootSession {
            get {
                return ResourceManager.GetString("ChangelogCategory_LootSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Feature.
        /// </summary>
        internal static string ChangelogCategory_NewFeature {
            get {
                return ResourceManager.GetString("ChangelogCategory_NewFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance.
        /// </summary>
        internal static string ChangelogCategory_Performance {
            get {
                return ResourceManager.GetString("ChangelogCategory_Performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string ChangelogCategory_System {
            get {
                return ResourceManager.GetString("ChangelogCategory_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Interface.
        /// </summary>
        internal static string ChangelogCategory_UserInterface {
            get {
                return ResourceManager.GetString("ChangelogCategory_UserInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show me all changes.
        /// </summary>
        internal static string ChangelogShowOption_ShowAll {
            get {
                return ResourceManager.GetString("ChangelogShowOption_ShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do NOT show changes.
        /// </summary>
        internal static string ChangelogShowOption_ShowNone {
            get {
                return ResourceManager.GetString("ChangelogShowOption_ShowNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show me notable changes.
        /// </summary>
        internal static string ChangelogShowOption_ShowNotable {
            get {
                return ResourceManager.GetString("ChangelogShowOption_ShowNotable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeah, I read it!.
        /// </summary>
        internal static string ChangeLogUi_btn_haveRead {
            get {
                return ResourceManager.GetString("ChangeLogUi_btn_haveRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Known Issues.
        /// </summary>
        internal static string ChangeLogUi_hdg_KnownIssues {
            get {
                return ResourceManager.GetString("ChangeLogUi_hdg_KnownIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous changelogs.
        /// </summary>
        internal static string ChangeLogUi_hdg_seen {
            get {
                return ResourceManager.GetString("ChangeLogUi_hdg_seen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        internal static string ChangeLogUi_hdg_version {
            get {
                return ResourceManager.GetString("ChangeLogUi_hdg_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixes issue #{0}.
        /// </summary>
        internal static string ChangeLogUi_text_issueLink {
            get {
                return ResourceManager.GetString("ChangeLogUi_text_issueLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open on GitHub.
        /// </summary>
        internal static string ChangeLogUi_text_issueLink_tooltip {
            get {
                return ResourceManager.GetString("ChangeLogUi_text_issueLink_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Himbeertoni Raid Tool Changelog.
        /// </summary>
        internal static string ChangeLogUi_Title {
            get {
                return ResourceManager.GetString("ChangeLogUi_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error upgrading Core configuration from version {0}.
        /// </summary>
        internal static string Chat_configUpgradeError {
            get {
                return ResourceManager.GetString("Chat_configUpgradeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands used for Himbeertoni Raid Tool:.
        /// </summary>
        internal static string Chat_help_heading {
            get {
                return ResourceManager.GetString("Chat_help_heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the changelog.
        /// </summary>
        internal static string command_hrt_changelog {
            get {
                return ResourceManager.GetString("command_hrt_changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prints usage information to chat.
        /// </summary>
        internal static string Command_hrt_help {
            get {
                return ResourceManager.GetString("Command_hrt_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the Configuration window.
        /// </summary>
        internal static string Command_hrt_options {
            get {
                return ResourceManager.GetString("Command_hrt_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Welcome Window with explanations on how to use.
        /// </summary>
        internal static string Command_hrt_welcome {
            get {
                return ResourceManager.GetString("Command_hrt_welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update sets from etro.gg periodically.
        /// </summary>
        internal static string ConfigUi_cb_autoEtroUpdate {
            get {
                return ResourceManager.GetString("ConfigUi_cb_autoEtroUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update gear when examining.
        /// </summary>
        internal static string ConfigUi_cb_examine {
            get {
                return ResourceManager.GetString("ConfigUi_cb_examine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide in combat.
        /// </summary>
        internal static string ConfigUi_cb_hideInCombat {
            get {
                return ResourceManager.GetString("ConfigUi_cb_hideInCombat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore gear under item level.
        /// </summary>
        internal static string ConfigUi_cb_ignoreCustomILvlGear {
            get {
                return ResourceManager.GetString("ConfigUi_cb_ignoreCustomILvlGear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore gear from previous tiers.
        /// </summary>
        internal static string ConfigUi_cb_ignorePrevTierGear {
            get {
                return ResourceManager.GetString("ConfigUi_cb_ignorePrevTierGear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically update own data.
        /// </summary>
        internal static string ConfigUi_cb_ownData {
            get {
                return ResourceManager.GetString("ConfigUi_cb_ownData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save periodically.
        /// </summary>
        internal static string ConfigUi_cb_periodicSave {
            get {
                return ResourceManager.GetString("ConfigUi_cb_periodicSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hides all windows while character is in combat.
        /// </summary>
        internal static string ConfigUi_cb_tt_hideInCombat {
            get {
                return ResourceManager.GetString("ConfigUi_cb_tt_hideInCombat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not downgrade gear in gear sets to items below item level threshold.
        /// </summary>
        internal static string ConfigUi_cb_tt_ignoreCustomILvlGear {
            get {
                return ResourceManager.GetString("ConfigUi_cb_tt_ignoreCustomILvlGear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not downgrade to gear items not from current raid tier.
        /// </summary>
        internal static string ConfigUi_cb_tt_ignorePrevTierGear {
            get {
                return ResourceManager.GetString("ConfigUi_cb_tt_ignorePrevTierGear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keeps gear and classes of logged in character up to date.
        /// </summary>
        internal static string ConfigUi_cb_tt_ownData {
            get {
                return ResourceManager.GetString("ConfigUi_cb_tt_ownData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saves all data of this plugin periodically. (Helps prevent losing data if your game
        ///            crashes)
        ///        .
        /// </summary>
        internal static string ConfigUi_cb_tt_periodicSave {
            get {
                return ResourceManager.GetString("ConfigUi_cb_tt_periodicSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update combat jobs.
        /// </summary>
        internal static string ConfigUi_cb_updateCombatJobs {
            get {
                return ResourceManager.GetString("ConfigUi_cb_updateCombatJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update disciple of hand jobs.
        /// </summary>
        internal static string ConfigUi_cb_updateDohJobs {
            get {
                return ResourceManager.GetString("ConfigUi_cb_updateDohJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update disciple of land jobs.
        /// </summary>
        internal static string ConfigUi_cb_updateDolJobs {
            get {
                return ResourceManager.GetString("ConfigUi_cb_updateDolJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Save.
        /// </summary>
        internal static string ConfigUi_hdg_AutoSave {
            get {
                return ResourceManager.GetString("ConfigUi_hdg_AutoSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changelog Options.
        /// </summary>
        internal static string ConfigUi_hdg_changelog {
            get {
                return ResourceManager.GetString("ConfigUi_hdg_changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic data update.
        /// </summary>
        internal static string ConfigUi_hdg_dataUpdate {
            get {
                return ResourceManager.GetString("ConfigUi_hdg_dataUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etro Gear Updates.
        /// </summary>
        internal static string ConfigUi_hdg_etroUpdates {
            get {
                return ResourceManager.GetString("ConfigUi_hdg_etroUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Interface.
        /// </summary>
        internal static string ConfigUi_hdg_ui {
            get {
                return ResourceManager.GetString("ConfigUi_hdg_ui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoSave interval (min).
        /// </summary>
        internal static string ConfigUi_in_autoSaveInterval {
            get {
                return ResourceManager.GetString("ConfigUi_in_autoSaveInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update interval (days).
        /// </summary>
        internal static string ConfigUi_in_etroUpdateInterval {
            get {
                return ResourceManager.GetString("ConfigUi_in_etroUpdateInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gear updates.
        /// </summary>
        internal static string ConfigUi_tab_GearUpdates {
            get {
                return ResourceManager.GetString("ConfigUi_tab_GearUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string ConfigUi_tab_general {
            get {
                return ResourceManager.GetString("ConfigUi_tab_general", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job specific config (affects all options above).
        /// </summary>
        internal static string ConfigUi_text_dataUpdateJobs {
            get {
                return ResourceManager.GetString("ConfigUi_text_dataUpdateJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core functionality of Himbeertoni Raid Tool.
        /// </summary>
        internal static string Module_Description {
            get {
                return ResourceManager.GetString("Module_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core Functions.
        /// </summary>
        internal static string Module_Name {
            get {
                return ResourceManager.GetString("Module_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data failed to save.
        /// </summary>
        internal static string UiMessage_PeriodicSaveFailed {
            get {
                return ResourceManager.GetString("UiMessage_PeriodicSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Saved successfully.
        /// </summary>
        internal static string UiMessage_PeriodicSaveSuccessful {
            get {
                return ResourceManager.GetString("UiMessage_PeriodicSaveSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string WelcomeUi_btn_close {
            get {
                return ResourceManager.GetString("WelcomeUi_btn_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open LootMaster.
        /// </summary>
        internal static string WelcomeUi_btn_OpenLootMaster {
            get {
                return ResourceManager.GetString("WelcomeUi_btn_OpenLootMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Options.
        /// </summary>
        internal static string WelcomeUi_btn_OpenOptions {
            get {
                return ResourceManager.GetString("WelcomeUi_btn_OpenOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Wiki.
        /// </summary>
        internal static string Welcomeui_btn_openWiki {
            get {
                return ResourceManager.GetString("Welcomeui_btn_openWiki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close this window.
        /// </summary>
        internal static string WelcomeUi_btn_tt_close {
            get {
                return ResourceManager.GetString("WelcomeUi_btn_tt_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open LootMaster main window (/lootmaster).
        /// </summary>
        internal static string WelcomeUi_btn_tt_OpenLootMaster {
            get {
                return ResourceManager.GetString("WelcomeUi_btn_tt_OpenLootMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show configuration options (/hrt config).
        /// </summary>
        internal static string WelcomeUi_btn_tt_OpenOptions {
            get {
                return ResourceManager.GetString("WelcomeUi_btn_tt_OpenOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the wiki in your browser.
        /// </summary>
        internal static string Welcomeui_btn_tt_openWiki {
            get {
                return ResourceManager.GetString("Welcomeui_btn_tt_openWiki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Himbeertoni Raid Tool. Your companion in managing your raid group. Start
        ///            your journey by opening LootMaster by typing &quot;/lootmaster&quot; (or &quot;/lm&quot;) in chat
        ///            (or the button below). There we already added your character for you. Next you can get
        ///            your current gear either by using the &quot;magnifying glass&quot; button or
        ///            by examining your character via right clicking. The plugin will always update the gear
        ///            for characters that were added to a group or [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WelcomeUi_text {
            get {
                return ResourceManager.GetString("WelcomeUi_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Himbeertoni Raid Tool.
        /// </summary>
        internal static string WelcomeUi_Title {
            get {
                return ResourceManager.GetString("WelcomeUi_Title", resourceCulture);
            }
        }
    }
}
