//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HimbeertoniRaidTool.Plugin.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GeneralLoc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralLoc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HimbeertoniRaidTool.Plugin.Localization.GeneralLoc", typeof(GeneralLoc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to edit.
        /// </summary>
        internal static string CalendarUi_tt_Click_to_edit {
            get {
                return ResourceManager.GetString("CalendarUi_tt_Click_to_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active session: .
        /// </summary>
        internal static string CalendarUi_txt_Active_session {
            get {
                return ResourceManager.GetString("CalendarUi_txt_Active_session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} classes.
        /// </summary>
        internal static string CharacterSearchUi_txt_classCount {
            get {
                return ResourceManager.GetString("CharacterSearchUi_txt_classCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string CommonTerms_All {
            get {
                return ResourceManager.GetString("CommonTerms_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BiS.
        /// </summary>
        internal static string CommonTerms_BiS {
            get {
                return ResourceManager.GetString("CommonTerms_BiS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difference.
        /// </summary>
        internal static string CommonTerms_Difference {
            get {
                return ResourceManager.GetString("CommonTerms_Difference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        internal static string CommonTerms_Empty {
            get {
                return ResourceManager.GetString("CommonTerms_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string CommonTerms_ExternalID {
            get {
                return ResourceManager.GetString("CommonTerms_ExternalID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food.
        /// </summary>
        internal static string CommonTerms_Food {
            get {
                return ResourceManager.GetString("CommonTerms_Food", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gear.
        /// </summary>
        internal static string CommonTerms_Gear {
            get {
                return ResourceManager.GetString("CommonTerms_Gear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Level.
        /// </summary>
        internal static string CommonTerms_itemLevel {
            get {
                return ResourceManager.GetString("CommonTerms_itemLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iLvl.
        /// </summary>
        internal static string CommonTerms_itemLvl_abbrev {
            get {
                return ResourceManager.GetString("CommonTerms_itemLvl_abbrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L.
        /// </summary>
        internal static string CommonTerms_Left_Abbrev {
            get {
                return ResourceManager.GetString("CommonTerms_Left_Abbrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        internal static string CommonTerms_Level {
            get {
                return ResourceManager.GetString("CommonTerms_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materia.
        /// </summary>
        internal static string CommonTerms_Materia {
            get {
                return ResourceManager.GetString("CommonTerms_Materia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string CommonTerms_Name {
            get {
                return ResourceManager.GetString("CommonTerms_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n.
        /// </summary>
        internal static string CommonTerms_No_Abbrev {
            get {
                return ResourceManager.GetString("CommonTerms_No_Abbrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string CommonTerms_None {
            get {
                return ResourceManager.GetString("CommonTerms_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R.
        /// </summary>
        internal static string CommonTerms_Right_Abbrev {
            get {
                return ResourceManager.GetString("CommonTerms_Right_Abbrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tribe.
        /// </summary>
        internal static string CommonTerms_Tribe {
            get {
                return ResourceManager.GetString("CommonTerms_Tribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to undefined.
        /// </summary>
        internal static string CommonTerms_undefined {
            get {
                return ResourceManager.GetString("CommonTerms_undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string CommonTerms_Unknown {
            get {
                return ResourceManager.GetString("CommonTerms_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y.
        /// </summary>
        internal static string CommonTerms_Yes_Abbrev {
            get {
                return ResourceManager.GetString("CommonTerms_Yes_Abbrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tried loading a configuration from a newer version of the plugin
        ///To prevent data loss operation has been stopped.
        ///You need to update to use this plugin!.
        /// </summary>
        internal static string Config_Error_Downgrade {
            get {
                return ResourceManager.GetString("Config_Error_Downgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HimbeerToni Raid Tool Configuration.
        /// </summary>
        internal static string ConfigUi_Title {
            get {
                return ResourceManager.GetString("ConfigUi_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished periodic {2} Updates. ({0}/{1}) updated.
        /// </summary>
        internal static string Connector_UpdateAllSets_Finished {
            get {
                return ResourceManager.GetString("Connector_UpdateAllSets_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select player.
        /// </summary>
        internal static string DBSearchPlayerUi_hdg_selectPlayer {
            get {
                return ResourceManager.GetString("DBSearchPlayerUi_hdg_selectPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently selected.
        /// </summary>
        internal static string DBSearchPlayerUi_txt_selected {
            get {
                return ResourceManager.GetString("DBSearchPlayerUi_txt_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select gear set from database.
        /// </summary>
        internal static string DBSearchWindowGear_Title {
            get {
                return ResourceManager.GetString("DBSearchWindowGear_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop costs.
        /// </summary>
        internal static string DrawItem_hdg_ShopCosts {
            get {
                return ResourceManager.GetString("DrawItem_hdg_ShopCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group that is organizing this session.
        /// </summary>
        internal static string EditaidSessuinUi_combo_tt_group {
            get {
                return ResourceManager.GetString("EditaidSessuinUi_combo_tt_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not show this job.
        /// </summary>
        internal static string EditCharUi_cb_hideJob {
            get {
                return ResourceManager.GetString("EditCharUi_cb_hideJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Data.
        /// </summary>
        internal static string EditCharUi_hdg_JobData {
            get {
                return ResourceManager.GetString("EditCharUi_hdg_JobData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home World.
        /// </summary>
        internal static string EditCharUi_in_HomeWorld {
            get {
                return ResourceManager.GetString("EditCharUi_in_HomeWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Job.
        /// </summary>
        internal static string EditCharUi_in_mainJob {
            get {
                return ResourceManager.GetString("EditCharUi_in_mainJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BiS sets are now changed by editing the respective BiS set directly.
        /// </summary>
        internal static string EditCharUi_text_BisNotice {
            get {
                return ResourceManager.GetString("EditCharUi_text_BisNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character does not have any classes created.
        /// </summary>
        internal static string EditCharUi_text_noJobs {
            get {
                return ResourceManager.GetString("EditCharUi_text_noJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        internal static string EditGearSetUi_btn_GetExternal {
            get {
                return ResourceManager.GetString("EditGearSetUi_btn_GetExternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create local copy.
        /// </summary>
        internal static string EditGearSetUi_btn_MakeLocal {
            get {
                return ResourceManager.GetString("EditGearSetUi_btn_MakeLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open set on etro.gg.
        /// </summary>
        internal static string EditGearSetUi_btn_openEtro {
            get {
                return ResourceManager.GetString("EditGearSetUi_btn_openEtro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open on {0}.
        /// </summary>
        internal static string EditGearSetUi_btn_OpenWeb {
            get {
                return ResourceManager.GetString("EditGearSetUi_btn_OpenWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get.
        /// </summary>
        internal static string EditGearSetUi_btn_tt_cutsomEtro {
            get {
                return ResourceManager.GetString("EditGearSetUi_btn_tt_cutsomEtro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download set.
        /// </summary>
        internal static string EditGearSetUi_btn_tt_cutsomEtro_Get {
            get {
                return ResourceManager.GetString("EditGearSetUi_btn_tt_cutsomEtro_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download set and replace current one.
        /// </summary>
        internal static string EditGearSetUi_btn_tt_GetExternal {
            get {
                return ResourceManager.GetString("EditGearSetUi_btn_tt_GetExternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a copy of this set in the local database. Set will not be updated from etro.gg
        ///            afterwards
        ///            Only local Gear Sets can be edited
        ///        .
        /// </summary>
        internal static string EditGearSetUi_btn_tt_MakeLocal {
            get {
                return ResourceManager.GetString("EditGearSetUi_btn_tt_MakeLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the set on the website of the external service in your default browser.
        /// </summary>
        internal static string EditGearSetUi_btn_tt_OpenWeb {
            get {
                return ResourceManager.GetString("EditGearSetUi_btn_tt_OpenWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select item.
        /// </summary>
        internal static string EditGearSetUi_btn_tt_selectItem {
            get {
                return ResourceManager.GetString("EditGearSetUi_btn_tt_selectItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supply own set.
        /// </summary>
        internal static string EditGearSetUi_hdg_ExtCustom {
            get {
                return ResourceManager.GetString("EditGearSetUi_hdg_ExtCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID/Url.
        /// </summary>
        internal static string EditGearSetUi_input_ExtId {
            get {
                return ResourceManager.GetString("EditGearSetUi_input_ExtId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string EditGearSetUi_Source {
            get {
                return ResourceManager.GetString("EditGearSetUi_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace with BiS from {0}.
        /// </summary>
        internal static string EditGearSetUi_text_getCuratedBis {
            get {
                return ResourceManager.GetString("EditGearSetUi_text_getCuratedBis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace with bis from etro.
        /// </summary>
        internal static string EditGearSetUi_text_getEtroBis {
            get {
                return ResourceManager.GetString("EditGearSetUi_text_getEtroBis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Id / Url.
        /// </summary>
        internal static string EditGearSetUi_text_InvalidId {
            get {
                return ResourceManager.GetString("EditGearSetUi_text_InvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace with:.
        /// </summary>
        internal static string EditGearSetUi_text_Replace {
            get {
                return ResourceManager.GetString("EditGearSetUi_text_Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Detect.
        /// </summary>
        internal static string EditGearSetUi_txt_AutoDetect {
            get {
                return ResourceManager.GetString("EditGearSetUi_txt_AutoDetect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gear set is meant for Job:.
        /// </summary>
        internal static string EditGearSetUi_txt_job {
            get {
                return ResourceManager.GetString("EditGearSetUi_txt_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Change.
        /// </summary>
        internal static string EditGearSetUi_txt_LastChange {
            get {
                return ResourceManager.GetString("EditGearSetUi_txt_LastChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last update check.
        /// </summary>
        internal static string EditGearSetUi_txt_lastUpdate {
            get {
                return ResourceManager.GetString("EditGearSetUi_txt_lastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string EditGearSetUi_txt_Loading {
            get {
                return ResourceManager.GetString("EditGearSetUi_txt_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string EditGearSetUi_txt_Source {
            get {
                return ResourceManager.GetString("EditGearSetUi_txt_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override role priority.
        /// </summary>
        internal static string EditGroupUi_cb_OverrideRolePriority {
            get {
                return ResourceManager.GetString("EditGroupUi_cb_OverrideRolePriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Type.
        /// </summary>
        internal static string EditGroupUi_in_type {
            get {
                return ResourceManager.GetString("EditGroupUi_in_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Main.
        /// </summary>
        internal static string EditPlayerUi_btn_IsMain {
            get {
                return ResourceManager.GetString("EditPlayerUi_btn_IsMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Main.
        /// </summary>
        internal static string EditPlayerUi_btn_MakeMain {
            get {
                return ResourceManager.GetString("EditPlayerUi_btn_MakeMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Data.
        /// </summary>
        internal static string EditPlayerUi_hdg_characterData {
            get {
                return ResourceManager.GetString("EditPlayerUi_hdg_characterData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Data.
        /// </summary>
        internal static string EditPlayerUi_hdg_playerData {
            get {
                return ResourceManager.GetString("EditPlayerUi_hdg_playerData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add all members.
        /// </summary>
        internal static string EditRaidSessionUi_btn_Add_all_members {
            get {
                return ResourceManager.GetString("EditRaidSessionUi_btn_Add_all_members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add all members of the group to the event.
        /// </summary>
        internal static string EditRaidSessionUi_btn_tt_Add_all_members {
            get {
                return ResourceManager.GetString("EditRaidSessionUi_btn_tt_Add_all_members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Instance.
        /// </summary>
        internal static string EditRaidSessionUi_cmb_AddInstance {
            get {
                return ResourceManager.GetString("EditRaidSessionUi_cmb_AddInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        internal static string EditRaidSessionUi_hdg_content {
            get {
                return ResourceManager.GetString("EditRaidSessionUi_hdg_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participants.
        /// </summary>
        internal static string EditRaidSessionUi_hdg_Participants {
            get {
                return ResourceManager.GetString("EditRaidSessionUi_hdg_Participants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loot.
        /// </summary>
        internal static string EditRaidSessionUi_tbh_hdg_loot {
            get {
                return ResourceManager.GetString("EditRaidSessionUi_tbh_hdg_loot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance.
        /// </summary>
        internal static string EditRaidSessionUi_tblHdg_Instance {
            get {
                return ResourceManager.GetString("EditRaidSessionUi_tblHdg_Instance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite Status.
        /// </summary>
        internal static string EditRaidSessionUi_txt_InviteStatus {
            get {
                return ResourceManager.GetString("EditRaidSessionUi_txt_InviteStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Killed? .
        /// </summary>
        internal static string EditRaidSessionUi_txt_Killed {
            get {
                return ResourceManager.GetString("EditRaidSessionUi_txt_Killed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not killed yet.
        /// </summary>
        internal static string EditRaidSessionUi_txt_Not_killed_yet {
            get {
                return ResourceManager.GetString("EditRaidSessionUi_txt_Not_killed_yet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing planned yet.
        /// </summary>
        internal static string EditRaidSessionUi_txt_Nothing_planned_yet {
            get {
                return ResourceManager.GetString("EditRaidSessionUi_txt_Nothing_planned_yet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participation.
        /// </summary>
        internal static string EditRaidSessionUi_txt_ParticipationStatus {
            get {
                return ResourceManager.GetString("EditRaidSessionUi_txt_ParticipationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan: .
        /// </summary>
        internal static string EditRaidSessionUi_txt_Plan {
            get {
                return ResourceManager.GetString("EditRaidSessionUi_txt_Plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set All.
        /// </summary>
        internal static string EditRaidSessionUi_txt_setAll {
            get {
                return ResourceManager.GetString("EditRaidSessionUi_txt_setAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit {0} {1}.
        /// </summary>
        internal static string EditUi_Title {
            get {
                return ResourceManager.GetString("EditUi_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local ID.
        /// </summary>
        internal static string EditUi_Txt_LocalId {
            get {
                return ResourceManager.GetString("EditUi_Txt_LocalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error fetching BiS list from etro.gg.
        /// </summary>
        internal static string EtroConnector_FillBisList_ErrorMessaeg {
            get {
                return ResourceManager.GetString("EtroConnector_FillBisList_ErrorMessaeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Successfully loaded BiS list from etro.gg.
        /// </summary>
        internal static string EtroConnector_FillBisList_Success {
            get {
                return ResourceManager.GetString("EtroConnector_FillBisList_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting materia info from etro.gg.
        /// </summary>
        internal static string EtroConnector_FillMateriaCache_Error {
            get {
                return ResourceManager.GetString("EtroConnector_FillMateriaCache_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully fetched materia definitions from etro.gg.
        /// </summary>
        internal static string EtroConnector_FillMateriaCache_Success {
            get {
                return ResourceManager.GetString("EtroConnector_FillMateriaCache_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update set {0}.
        /// </summary>
        internal static string EtroConnector_GetGearSet_Error {
            get {
                return ResourceManager.GetString("EtroConnector_GetGearSet_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot handle relic item for slot: {0}.
        /// </summary>
        internal static string EtroConnector_GetGearSet_RelicError {
            get {
                return ResourceManager.GetString("EtroConnector_GetGearSet_RelicError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Update from Etro for {0} succeeded.
        /// </summary>
        internal static string EtroConnector_GetGearSet_Success {
            get {
                return ResourceManager.GetString("EtroConnector_GetGearSet_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This set originated from an external service and will be automatically updated from there. IF you want to make edits you need to make a local copy..
        /// </summary>
        internal static string Gearset_Warning_ExternalManaged {
            get {
                return ResourceManager.GetString("Gearset_Warning_ExternalManaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This set is manged by the plugin and will be automatically overwritten with characters current gear!.
        /// </summary>
        internal static string Gearset_Warning_SysManaged {
            get {
                return ResourceManager.GetString("Gearset_Warning_SysManaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string General_btn_tt_close {
            get {
                return ResourceManager.GetString("General_btn_tt_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0} {1}.
        /// </summary>
        internal static string General_btn_tt_delete {
            get {
                return ResourceManager.GetString("General_btn_tt_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit {0} {1}.
        /// </summary>
        internal static string General_btn_tt_edit {
            get {
                return ResourceManager.GetString("General_btn_tt_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove {0} {1}.
        /// </summary>
        internal static string General_btn_tt_remove {
            get {
                return ResourceManager.GetString("General_btn_tt_remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string General_btn_tt_save {
            get {
                return ResourceManager.GetString("General_btn_tt_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string GeneralTerm_Date {
            get {
                return ResourceManager.GetString("GeneralTerm_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        internal static string GeneralTerm_Day {
            get {
                return ResourceManager.GetString("GeneralTerm_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string GeneralTerm_Duration {
            get {
                return ResourceManager.GetString("GeneralTerm_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group:.
        /// </summary>
        internal static string GeneralTerm_Group {
            get {
                return ResourceManager.GetString("GeneralTerm_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        internal static string GeneralTerm_Hour {
            get {
                return ResourceManager.GetString("GeneralTerm_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute.
        /// </summary>
        internal static string GeneralTerm_Minute {
            get {
                return ResourceManager.GetString("GeneralTerm_Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        internal static string GeneralTerm_Month {
            get {
                return ResourceManager.GetString("GeneralTerm_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all.
        /// </summary>
        internal static string GeneralTerm_Show_all {
            get {
                return ResourceManager.GetString("GeneralTerm_Show_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string GeneralTerm_Time {
            get {
                return ResourceManager.GetString("GeneralTerm_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string GeneralTerm_Year {
            get {
                return ResourceManager.GetString("GeneralTerm_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance.
        /// </summary>
        internal static string GeneralTerms_Instance {
            get {
                return ResourceManager.GetString("GeneralTerms_Instance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get character from DB.
        /// </summary>
        internal static string GetCharacterWindow_Title {
            get {
                return ResourceManager.GetString("GetCharacterWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Savage Books.
        /// </summary>
        internal static string InventoryWindow_Hdg_Current_Savage_Books {
            get {
                return ResourceManager.GetString("InventoryWindow_Hdg_Current_Savage_Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header.
        /// </summary>
        internal static string ItemTable_heading_Header {
            get {
                return ResourceManager.GetString("ItemTable_heading_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looted in.
        /// </summary>
        internal static string ItemTable_heading_LootedIn {
            get {
                return ResourceManager.GetString("ItemTable_heading_LootedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string ItemTable_heading_name {
            get {
                return ResourceManager.GetString("ItemTable_heading_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string ItemTable_heading_source {
            get {
                return ResourceManager.GetString("ItemTable_heading_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started gear update for.
        /// </summary>
        internal static string LodestonConnetor_msg_UpdateStarted {
            get {
                return ResourceManager.GetString("LodestonConnetor_msg_UpdateStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character not found on Lodestone..
        /// </summary>
        internal static string LodestoneConnector_err_CharNotFound {
            get {
                return ResourceManager.GetString("LodestoneConnector_err_CharNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create new gear set..
        /// </summary>
        internal static string LodestoneConnector_err_FailedToCreateGear {
            get {
                return ResourceManager.GetString("LodestoneConnector_err_FailedToCreateGear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update gear from Lodestone..
        /// </summary>
        internal static string LodestoneConnector_err_GeneralFailure {
            get {
                return ResourceManager.GetString("LodestoneConnector_err_GeneralFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not resolve currently used job or currently displayed job on Lodestone is not
        ///            supported.
        ///        .
        /// </summary>
        internal static string LodestoneConnector_err_JobIncompatible {
            get {
                return ResourceManager.GetString("LodestoneConnector_err_JobIncompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated {0}&apos;s {1} gear from Lodestone..
        /// </summary>
        internal static string LodestoneConnector_msg_Success {
            get {
                return ResourceManager.GetString("LodestoneConnector_msg_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string RaidSessionSearchUi_dhg_Title {
            get {
                return ResourceManager.GetString("RaidSessionSearchUi_dhg_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participants.
        /// </summary>
        internal static string RaidSessionSearchUi_hdg_Participants {
            get {
                return ResourceManager.GetString("RaidSessionSearchUi_hdg_Participants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select {0} {1}.
        /// </summary>
        internal static string SearchWindow_btn_tt_SelectEnty {
            get {
                return ResourceManager.GetString("SearchWindow_btn_tt_SelectEnty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get item for.
        /// </summary>
        internal static string SelectGearItemui_Title {
            get {
                return ResourceManager.GetString("SelectGearItemui_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this item.
        /// </summary>
        internal static string SelectItemUi_btn_tt_useThis {
            get {
                return ResourceManager.GetString("SelectItemUi_btn_tt_useThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing chosen.
        /// </summary>
        internal static string SelectItemWindow_SaveBtn_tt_Nothing_chosen {
            get {
                return ResourceManager.GetString("SelectItemWindow_SaveBtn_tt_Nothing_chosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose loot from {0}.
        /// </summary>
        internal static string SelectLootItemWindow_Title {
            get {
                return ResourceManager.GetString("SelectLootItemWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select materia.
        /// </summary>
        internal static string SelectMateriaUi_Title {
            get {
                return ResourceManager.GetString("SelectMateriaUi_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move {0} down.
        /// </summary>
        internal static string SortableList_btn_tt_moveDown {
            get {
                return ResourceManager.GetString("SortableList_btn_tt_moveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move {0} up.
        /// </summary>
        internal static string SortableList_btn_tt_moveUp {
            get {
                return ResourceManager.GetString("SortableList_btn_tt_moveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Gear by Examining.
        /// </summary>
        internal static string Ui_btn_Inspect_tt {
            get {
                return ResourceManager.GetString("Ui_btn_Inspect_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add {0}.
        /// </summary>
        internal static string Ui_btn_tt_add {
            get {
                return ResourceManager.GetString("Ui_btn_tt_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add empty {0}.
        /// </summary>
        internal static string Ui_btn_tt_addEmpty {
            get {
                return ResourceManager.GetString("Ui_btn_tt_addEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add {0} from database.
        /// </summary>
        internal static string Ui_btn_tt_addExisting {
            get {
                return ResourceManager.GetString("Ui_btn_tt_addExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Ui_btn_tt_cancel {
            get {
                return ResourceManager.GetString("Ui_btn_tt_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character is not in reach to examine.
        /// </summary>
        internal static string Ui_btn_tt_CharacterNotInReach {
            get {
                return ResourceManager.GetString("Ui_btn_tt_CharacterNotInReach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update {0} ({1}) from etro.
        /// </summary>
        internal static string Ui_btn_tt_etroUpdate {
            get {
                return ResourceManager.GetString("Ui_btn_tt_etroUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update {0} ({1}) from {2}.
        /// </summary>
        internal static string Ui_btn_tt_GearSetUpdate {
            get {
                return ResourceManager.GetString("Ui_btn_tt_GearSetUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Gear from Lodestone.
        /// </summary>
        internal static string Ui_btn_tt_Lodestone {
            get {
                return ResourceManager.GetString("Ui_btn_tt_Lodestone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove {0} from {1}.
        /// </summary>
        internal static string Ui_btn_tt_removeFrom {
            get {
                return ResourceManager.GetString("Ui_btn_tt_removeFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update &quot;{0}&quot; from Etro.gg.
        /// </summary>
        internal static string Ui_btn_tt_UpdateFrmEtro {
            get {
                return ResourceManager.GetString("Ui_btn_tt_UpdateFrmEtro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update &quot;{0}&quot; ({1}) from XivGear.app.
        /// </summary>
        internal static string Ui_btn_tt_XivGearUpdate {
            get {
                return ResourceManager.GetString("Ui_btn_tt_XivGearUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select materia.
        /// </summary>
        internal static string Ui_GearEdit_btn_tt_selectMat {
            get {
                return ResourceManager.GetString("Ui_GearEdit_btn_tt_selectMat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to press shift to be able to click this button.
        /// </summary>
        internal static string Ui_GuardedButton_notice {
            get {
                return ResourceManager.GetString("Ui_GuardedButton_notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to right click for more options.
        /// </summary>
        internal static string Ui_rightClickHint {
            get {
                return ResourceManager.GetString("Ui_rightClickHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Add known {0}.
        /// </summary>
        internal static string UiHelpers_txt_AddKnown {
            get {
                return ResourceManager.GetString("UiHelpers_txt_AddKnown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Add new {0}.
        /// </summary>
        internal static string UiHelpers_txt_AddNew {
            get {
                return ResourceManager.GetString("UiHelpers_txt_AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace with known {0}.
        /// </summary>
        internal static string UiHelpers_txt_ReplaceKnown {
            get {
                return ResourceManager.GetString("UiHelpers_txt_ReplaceKnown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace with new {0}.
        /// </summary>
        internal static string UiHelpers_txt_ReplaceNew {
            get {
                return ResourceManager.GetString("UiHelpers_txt_ReplaceNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating set {0} from XivGear.app.
        /// </summary>
        internal static string XivGearAppConnector_GetGearSet_Error {
            get {
                return ResourceManager.GetString("XivGearAppConnector_GetGearSet_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update from XivGear.app for {0} succeeded.
        /// </summary>
        internal static string XivGearAppConnector_GetGearSet_Success {
            get {
                return ResourceManager.GetString("XivGearAppConnector_GetGearSet_Success", resourceCulture);
            }
        }
    }
}
