//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HimbeertoniRaidTool.Plugin.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GeneralLoc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralLoc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HimbeertoniRaidTool.Plugin.Localization.GeneralLoc", typeof(GeneralLoc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to default.
        /// </summary>
        internal static string _default {
            get {
                return ResourceManager.GetString("default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Player.
        /// </summary>
        internal static string Add_Player {
            get {
                return ResourceManager.GetString("Add Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        internal static string Appearance {
            get {
                return ResourceManager.GetString("Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BiS.
        /// </summary>
        internal static string BiS {
            get {
                return ResourceManager.GetString("BiS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous changelogs.
        /// </summary>
        internal static string ChangeLogUi_heading_seen {
            get {
                return ResourceManager.GetString("ChangeLogUi_heading_seen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Himbeertoni Raid Tool Changelog.
        /// </summary>
        internal static string ChangeLogUi_Title {
            get {
                return ResourceManager.GetString("ChangeLogUi_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Name.
        /// </summary>
        internal static string Character_Name {
            get {
                return ResourceManager.GetString("Character Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands used for Loot Master:.
        /// </summary>
        internal static string chat_usage_heading {
            get {
                return ResourceManager.GetString("chat_usage_heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the changelog.
        /// </summary>
        internal static string command_hrt_changelog {
            get {
                return ResourceManager.GetString("command_hrt_changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens Lootmaster window.
        /// </summary>
        internal static string command_show_helpText {
            get {
                return ResourceManager.GetString("command_show_helpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggles Lootmaster window.
        /// </summary>
        internal static string command_toggle_helpText {
            get {
                return ResourceManager.GetString("command_toggle_helpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tried loading a configuration from a newer version of the plugin
        ///To prevent data loss operation has been stopped.
        ///You need to update to use this plugin!.
        /// </summary>
        internal static string Config_Error_Downgrade {
            get {
                return ResourceManager.GetString("Config_Error_Downgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HimbeerToni Raid Tool Configuration.
        /// </summary>
        internal static string ConfigWindow_Title {
            get {
                return ResourceManager.GetString("ConfigWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Confirm_action {
            get {
                return ResourceManager.GetString("Confirm action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core functionality of Himbeertoni Raid Tool.
        /// </summary>
        internal static string CoreModule_Description {
            get {
                return ResourceManager.GetString("CoreModule_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core Functions.
        /// </summary>
        internal static string CoreModule_Name {
            get {
                return ResourceManager.GetString("CoreModule_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These sets are used when creating a new character or adding a new job. These do not
        ///            affect already created characters and jobs.
        ///        .
        /// </summary>
        internal static string DefaultBiSDisclaimer {
            get {
                return ResourceManager.GetString("DefaultBiSDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default BiS sets (as etro.gg ID).
        /// </summary>
        internal static string DefaultBiSHeading {
            get {
                return ResourceManager.GetString("DefaultBiSHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetch default BiS from configuration.
        /// </summary>
        internal static string DefaultBiSTooltip {
            get {
                return ResourceManager.GetString("DefaultBiSTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete following player?.
        /// </summary>
        internal static string DeletePlayerConfirmation {
            get {
                return ResourceManager.GetString("DeletePlayerConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Dmg with a 100 potency skill adjusted for faster GCDs.
        /// </summary>
        internal static string Dmgper100Tooltip {
            get {
                return ResourceManager.GetString("Dmgper100Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop costs.
        /// </summary>
        internal static string DrawItem_heading_ShopCosts {
            get {
                return ResourceManager.GetString("DrawItem_heading_ShopCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit group.
        /// </summary>
        internal static string Edit_group {
            get {
                return ResourceManager.GetString("Edit group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit player.
        /// </summary>
        internal static string Edit_player {
            get {
                return ResourceManager.GetString("Edit player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not show this job.
        /// </summary>
        internal static string EditCharacterui_input_hideJob {
            get {
                return ResourceManager.GetString("EditCharacterui_input_hideJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add job.
        /// </summary>
        internal static string EditCharacterWindow_button_addJob_tooltip {
            get {
                return ResourceManager.GetString("EditCharacterWindow_button_addJob_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all data for {0}.
        /// </summary>
        internal static string EditCharacterWindow_button_deleteJob_tooltip {
            get {
                return ResourceManager.GetString("EditCharacterWindow_button_deleteJob_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Data.
        /// </summary>
        internal static string EditCharacterWindow_heading_JobData {
            get {
                return ResourceManager.GetString("EditCharacterWindow_heading_JobData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Job.
        /// </summary>
        internal static string EditCharacterWindow_input_AddJob {
            get {
                return ResourceManager.GetString("EditCharacterWindow_input_AddJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Job.
        /// </summary>
        internal static string EditCharacterWindow_input_mainJob {
            get {
                return ResourceManager.GetString("EditCharacterWindow_input_mainJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BiS sets are now changed by editing the respective BiS set directly.
        /// </summary>
        internal static string EditCharacterWindow_text_BisNotice {
            get {
                return ResourceManager.GetString("EditCharacterWindow_text_BisNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character does not have any classes created.
        /// </summary>
        internal static string EditCharacterWindow_text_noJobs {
            get {
                return ResourceManager.GetString("EditCharacterWindow_text_noJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit character {0}.
        /// </summary>
        internal static string EditCharacterWindow_Title {
            get {
                return ResourceManager.GetString("EditCharacterWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open set on etro.gg.
        /// </summary>
        internal static string EditGearSetUi_btn_openEtro {
            get {
                return ResourceManager.GetString("EditGearSetUi_btn_openEtro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Change: {0}.
        /// </summary>
        internal static string EditGearSetUi_txt_LastChange {
            get {
                return ResourceManager.GetString("EditGearSetUi_txt_LastChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last update check: {0}.
        /// </summary>
        internal static string EditGearSetUi_txt_lastUpdate {
            get {
                return ResourceManager.GetString("EditGearSetUi_txt_lastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string EditGearSetUi_txt_Source {
            get {
                return ResourceManager.GetString("EditGearSetUi_txt_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string EditGearSetWindow_button_CustomEtro {
            get {
                return ResourceManager.GetString("EditGearSetWindow_button_CustomEtro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide custom id.
        /// </summary>
        internal static string EditGearSetWindow_button_CustomEtro_tooltip {
            get {
                return ResourceManager.GetString("EditGearSetWindow_button_CustomEtro_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get.
        /// </summary>
        internal static string EditGearSetWindow_cutsomEtro_button_Get {
            get {
                return ResourceManager.GetString("EditGearSetWindow_cutsomEtro_button_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download set.
        /// </summary>
        internal static string EditGearSetWindow_cutsomEtro_button_Get_tooltip {
            get {
                return ResourceManager.GetString("EditGearSetWindow_cutsomEtro_button_Get_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace with set from etro.
        /// </summary>
        internal static string EditGearSetWindow_text_getEtro {
            get {
                return ResourceManager.GetString("EditGearSetWindow_text_getEtro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit gear set {0}.
        /// </summary>
        internal static string EditGearSetWindow_Title {
            get {
                return ResourceManager.GetString("EditGearSetWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Name.
        /// </summary>
        internal static string EditGroupWindow_input_name {
            get {
                return ResourceManager.GetString("EditGroupWindow_input_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Type.
        /// </summary>
        internal static string EditGroupWindow_input_type {
            get {
                return ResourceManager.GetString("EditGroupWindow_input_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Group {0}.
        /// </summary>
        internal static string EditGroupWindow_Title {
            get {
                return ResourceManager.GetString("EditGroupWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add custom character.
        /// </summary>
        internal static string EditPlayerWindow_button_AddEmptyCharacter_tooltip {
            get {
                return ResourceManager.GetString("EditPlayerWindow_button_AddEmptyCharacter_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add existing character.
        /// </summary>
        internal static string EditPlayerWindow_button_AddFromDb_tooltip {
            get {
                return ResourceManager.GetString("EditPlayerWindow_button_AddFromDb_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Edit {0} @ {1}.
        /// </summary>
        internal static string EditPlayerWindow_button_editChar_tooltip {
            get {
                return ResourceManager.GetString("EditPlayerWindow_button_editChar_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Main.
        /// </summary>
        internal static string EditPlayerWindow_button_IsMain {
            get {
                return ResourceManager.GetString("EditPlayerWindow_button_IsMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Main.
        /// </summary>
        internal static string EditPlayerWindow_button_MakeMain {
            get {
                return ResourceManager.GetString("EditPlayerWindow_button_MakeMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove {0} from {1}.
        /// </summary>
        internal static string EditPlayerWindow_button_removeChar_tooltip {
            get {
                return ResourceManager.GetString("EditPlayerWindow_button_removeChar_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Data.
        /// </summary>
        internal static string EditPlayerWindow_heading_characterData {
            get {
                return ResourceManager.GetString("EditPlayerWindow_heading_characterData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Data.
        /// </summary>
        internal static string EditPlayerWindow_heading_playerData {
            get {
                return ResourceManager.GetString("EditPlayerWindow_heading_playerData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Name.
        /// </summary>
        internal static string EditPlayerWindow_input_Name {
            get {
                return ResourceManager.GetString("EditPlayerWindow_input_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        internal static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etro ID.
        /// </summary>
        internal static string Etro_ID {
            get {
                return ResourceManager.GetString("Etro ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error fetching BiS list from etro.gg.
        /// </summary>
        internal static string EtroConnector_FillBisList_ErrorMessaeg {
            get {
                return ResourceManager.GetString("EtroConnector_FillBisList_ErrorMessaeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Successfully loaded BiS list from etro.gg.
        /// </summary>
        internal static string EtroConnector_FillBisList_Success {
            get {
                return ResourceManager.GetString("EtroConnector_FillBisList_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting materia info from etro.gg.
        /// </summary>
        internal static string EtroConnector_FillMateriaCache_Error {
            get {
                return ResourceManager.GetString("EtroConnector_FillMateriaCache_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully fetched materia definitions from etro.gg.
        /// </summary>
        internal static string EtroConnector_FillMateriaCache_Success {
            get {
                return ResourceManager.GetString("EtroConnector_FillMateriaCache_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update set {0}.
        /// </summary>
        internal static string EtroConnector_GetGearSet_Error {
            get {
                return ResourceManager.GetString("EtroConnector_GetGearSet_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot handle relic item for slot: {0}.
        /// </summary>
        internal static string EtroConnector_GetGearSet_RelicError {
            get {
                return ResourceManager.GetString("EtroConnector_GetGearSet_RelicError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Update from Etro for {0} succeeded.
        /// </summary>
        internal static string EtroConnector_GetGearSet_Success {
            get {
                return ResourceManager.GetString("EtroConnector_GetGearSet_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished periodic etro Updates. ({0}/{1}) updated.
        /// </summary>
        internal static string EtroConnector_UpdateEtroSets_Finished {
            get {
                return ResourceManager.GetString("EtroConnector_UpdateEtroSets_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gear.
        /// </summary>
        internal static string Gear {
            get {
                return ResourceManager.GetString("Gear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to etro.gg.
        /// </summary>
        internal static string GearSet_ManagedBy_Etro {
            get {
                return ResourceManager.GetString("GearSet:ManagedBy:Etro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Database.
        /// </summary>
        internal static string GearSet_ManagedBy_HrtLocal {
            get {
                return ResourceManager.GetString("GearSet:ManagedBy:HrtLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Database.
        /// </summary>
        internal static string GearSet_manager_local {
            get {
                return ResourceManager.GetString("GearSet_manager_local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This set is manged by the plugin and will be automatically overwritten with characters current gear!.
        /// </summary>
        internal static string Gearset_Warning_SysManaged {
            get {
                return ResourceManager.GetString("Gearset_Warning_SysManaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove set from this character (Hold Shift).
        /// </summary>
        internal static string GearsetEdit_Delete {
            get {
                return ResourceManager.GetString("GearsetEdit:Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last update check.
        /// </summary>
        internal static string GearSetEdit_EtroLastDownload {
            get {
                return ResourceManager.GetString("GearSetEdit:EtroLastDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Change.
        /// </summary>
        internal static string GearSetEdit_LastChanged {
            get {
                return ResourceManager.GetString("GearSetEdit:LastChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create local copy.
        /// </summary>
        internal static string GearSetEdit_MakeLocal {
            get {
                return ResourceManager.GetString("GearSetEdit:MakeLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a copy of this set in the local database. Set will not be updated from etro.gg
        ///            afterwards
        ///            Only local Gear Sets can be edited
        ///        .
        /// </summary>
        internal static string GearSetEdit_MakeLocal_tooltip {
            get {
                return ResourceManager.GetString("GearSetEdit:MakeLocal:tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string GearSetEdit_Name {
            get {
                return ResourceManager.GetString("GearSetEdit:Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string GearSetEditWindow_Source {
            get {
                return ResourceManager.GetString("GearSetEditWindow_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get item for.
        /// </summary>
        internal static string Get_item_for {
            get {
                return ResourceManager.GetString("Get item for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get character from DB.
        /// </summary>
        internal static string GetCharacterWindow_Title {
            get {
                return ResourceManager.GetString("GetCharacterWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home World.
        /// </summary>
        internal static string Home_World {
            get {
                return ResourceManager.GetString("Home World", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iLvl.
        /// </summary>
        internal static string iLvl {
            get {
                return ResourceManager.GetString("iLvl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Gear.
        /// </summary>
        internal static string Inventory_AdditionalGear {
            get {
                return ResourceManager.GetString("Inventory:AdditionalGear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Level.
        /// </summary>
        internal static string itemLevelLong {
            get {
                return ResourceManager.GetString("itemLevelLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iLvl.
        /// </summary>
        internal static string itemLevelShort {
            get {
                return ResourceManager.GetString("itemLevelShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header.
        /// </summary>
        internal static string ItemTable_heading_Header {
            get {
                return ResourceManager.GetString("ItemTable_heading_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Level.
        /// </summary>
        internal static string ItemTable_heading_iLvl {
            get {
                return ResourceManager.GetString("ItemTable_heading_iLvl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looted in.
        /// </summary>
        internal static string ItemTable_heading_LootedIn {
            get {
                return ResourceManager.GetString("ItemTable_heading_LootedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string ItemTable_heading_name {
            get {
                return ResourceManager.GetString("ItemTable_heading_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string ItemTable_heading_source {
            get {
                return ResourceManager.GetString("ItemTable_heading_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header.
        /// </summary>
        internal static string ItemTableHeader {
            get {
                return ResourceManager.GetString("ItemTableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L.
        /// </summary>
        internal static string Left_Abbrev {
            get {
                return ResourceManager.GetString("Left_Abbrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        internal static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local ID.
        /// </summary>
        internal static string Local_ID {
            get {
                return ResourceManager.GetString("Local ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Gear from Lodestone.
        /// </summary>
        internal static string Lodestone_Button {
            get {
                return ResourceManager.GetString("Lodestone Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character not found on Lodestone..
        /// </summary>
        internal static string LodestoneConnector_CharNotFound {
            get {
                return ResourceManager.GetString("LodestoneConnector:CharNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create new gear set..
        /// </summary>
        internal static string LodestoneConnector_FailedToCreateGear {
            get {
                return ResourceManager.GetString("LodestoneConnector:FailedToCreateGear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update gear from Lodestone..
        /// </summary>
        internal static string LodestoneConnector_Failure {
            get {
                return ResourceManager.GetString("LodestoneConnector:Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not resolve currently used job or currently displayed job on Lodestone is not
        ///            supported.
        ///        .
        /// </summary>
        internal static string LodestoneConnector_JobIncompatible {
            get {
                return ResourceManager.GetString("LodestoneConnector:JobIncompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated {0}&apos;s {1} gear from Lodestone..
        /// </summary>
        internal static string LodestoneConnector_Success {
            get {
                return ResourceManager.GetString("LodestoneConnector:Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started gear update for.
        /// </summary>
        internal static string LodestonUpdateStarted {
            get {
                return ResourceManager.GetString("LodestonUpdateStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit character {0}.
        /// </summary>
        internal static string LootmasterUi_button_editCharacter_tooltip {
            get {
                return ResourceManager.GetString("LootmasterUi_button_editCharacter_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit player {0}.
        /// </summary>
        internal static string LootmasterUi_button_editPlayer_tooltip {
            get {
                return ResourceManager.GetString("LootmasterUi_button_editPlayer_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materia.
        /// </summary>
        internal static string Materia {
            get {
                return ResourceManager.GetString("Materia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needed items.
        /// </summary>
        internal static string Needed_items {
            get {
                return ResourceManager.GetString("Needed items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n.
        /// </summary>
        internal static string No_Abbrev {
            get {
                return ResourceManager.GetString("No_Abbrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not defined.
        /// </summary>
        internal static string Not_defined {
            get {
                return ResourceManager.GetString("Not defined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n.A..
        /// </summary>
        internal static string NotAvail_Abbrev {
            get {
                return ResourceManager.GetString("NotAvail_Abbrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override role priority.
        /// </summary>
        internal static string Override_role_priority {
            get {
                return ResourceManager.GetString("Override role priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        internal static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show player details for.
        /// </summary>
        internal static string PlayerDetails {
            get {
                return ResourceManager.GetString("PlayerDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Details for {0}.
        /// </summary>
        internal static string PlayerDetailsTitle {
            get {
                return ResourceManager.GetString("PlayerDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BiS set for this class is locally managed.
        ///            Delete local set to use a set from etro.gg
        ///        .
        /// </summary>
        internal static string PlayerEdit_Tooltip_LocalBis {
            get {
                return ResourceManager.GetString("PlayerEdit:Tooltip:LocalBis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select player.
        /// </summary>
        internal static string PlayerSearchWindow_Select_player {
            get {
                return ResourceManager.GetString("PlayerSearchWindow_Select_player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently selected.
        /// </summary>
        internal static string PlayerSearchWindow_Selected {
            get {
                return ResourceManager.GetString("PlayerSearchWindow_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pos.
        /// </summary>
        internal static string Pos {
            get {
                return ResourceManager.GetString("Pos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this item.
        /// </summary>
        internal static string Remove_this_item {
            get {
                return ResourceManager.GetString("Remove this item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this materia.
        /// </summary>
        internal static string Remove_this_materia {
            get {
                return ResourceManager.GetString("Remove this materia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to default.
        /// </summary>
        internal static string Reset_to_default {
            get {
                return ResourceManager.GetString("Reset to default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results for.
        /// </summary>
        internal static string Results_for {
            get {
                return ResourceManager.GetString("Results for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R.
        /// </summary>
        internal static string Right_Abbrev {
            get {
                return ResourceManager.GetString("Right_Abbrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to right click for more options.
        /// </summary>
        internal static string rightClickHint {
            get {
                return ResourceManager.GetString("rightClickHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule.
        /// </summary>
        internal static string Rule {
            get {
                return ResourceManager.GetString("Rule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Player.
        /// </summary>
        internal static string Save_Player {
            get {
                return ResourceManager.GetString("Save Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select item.
        /// </summary>
        internal static string Select_item {
            get {
                return ResourceManager.GetString("Select item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select materia.
        /// </summary>
        internal static string SelectMateriaUi_Title {
            get {
                return ResourceManager.GetString("SelectMateriaUi_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set to default.
        /// </summary>
        internal static string Set_to_default {
            get {
                return ResourceManager.GetString("Set to default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add entry.
        /// </summary>
        internal static string SortableList_Add {
            get {
                return ResourceManager.GetString("SortableList_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move down.
        /// </summary>
        internal static string SortableList_moveDown {
            get {
                return ResourceManager.GetString("SortableList_moveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move up.
        /// </summary>
        internal static string SortableList_moveUp {
            get {
                return ResourceManager.GetString("SortableList_moveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove entry.
        /// </summary>
        internal static string SortableList_remove {
            get {
                return ResourceManager.GetString("SortableList_remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap players positions.
        /// </summary>
        internal static string Swap_players_positions {
            get {
                return ResourceManager.GetString("Swap players positions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap Position of.
        /// </summary>
        internal static string Swap_Position_of {
            get {
                return ResourceManager.GetString("Swap Position of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tribe.
        /// </summary>
        internal static string Tribe {
            get {
                return ResourceManager.GetString("Tribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Gear by Examining.
        /// </summary>
        internal static string Ui_btn_Inspect_tt {
            get {
                return ResourceManager.GetString("Ui_btn_Inspect_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character is not in reach to examine.
        /// </summary>
        internal static string Ui_btn_tt_CharacterNotInReach {
            get {
                return ResourceManager.GetString("Ui_btn_tt_CharacterNotInReach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select materia.
        /// </summary>
        internal static string Ui_GearEdit_btn_tt_selectMat {
            get {
                return ResourceManager.GetString("Ui_GearEdit_btn_tt_selectMat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to undefined.
        /// </summary>
        internal static string undefined {
            get {
                return ResourceManager.GetString("undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this item.
        /// </summary>
        internal static string Use_this_item {
            get {
                return ResourceManager.GetString("Use this item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World.
        /// </summary>
        internal static string World {
            get {
                return ResourceManager.GetString("World", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y.
        /// </summary>
        internal static string Yes_Abbrev {
            get {
                return ResourceManager.GetString("Yes_Abbrev", resourceCulture);
            }
        }
    }
}
