//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HimbeertoniRaidTool.Plugin.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LootmasterLoc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LootmasterLoc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HimbeertoniRaidTool.Plugin.Localization.LootmasterLoc", typeof(LootmasterLoc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Created.
        /// </summary>
        internal static string AutoCreatedGroupName {
            get {
                return ResourceManager.GetString("AutoCreatedGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands used for Loot Master:.
        /// </summary>
        internal static string chat_usage_heading {
            get {
                return ResourceManager.GetString("chat_usage_heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens LootMaster Window (or /lm as short variant).
        /// </summary>
        internal static string command_lootmaster {
            get {
                return ResourceManager.GetString("command_lootmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens Lootmaster window.
        /// </summary>
        internal static string command_show_helpText {
            get {
                return ResourceManager.GetString("command_show_helpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggles Lootmaster window.
        /// </summary>
        internal static string command_toggle_helpText {
            get {
                return ResourceManager.GetString("command_toggle_helpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore Materia.
        /// </summary>
        internal static string Config_cb_IgnoreMateriaForBis {
            get {
                return ResourceManager.GetString("Config_cb_IgnoreMateriaForBis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examples.
        /// </summary>
        internal static string Config_hdg_Examples {
            get {
                return ResourceManager.GetString("Config_hdg_Examples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color items by item level.
        /// </summary>
        internal static string ConfigUi_cb_ColoredItemNames {
            get {
                return ResourceManager.GetString("ConfigUi_cb_ColoredItemNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show item icon in group overview.
        /// </summary>
        internal static string ConfigUi_cb_IconInGroupOverview {
            get {
                return ResourceManager.GetString("ConfigUi_cb_IconInGroupOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open group overview on login.
        /// </summary>
        internal static string Configui_cb_OpenOnLogin {
            get {
                return ResourceManager.GetString("Configui_cb_OpenOnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color items according to the item level.
        /// </summary>
        internal static string ConfigUi_cb_tt_ColoredItemNames {
            get {
                return ResourceManager.GetString("ConfigUi_cb_tt_ColoredItemNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore Materia when determining if an item is equivalent to BiS.
        /// </summary>
        internal static string ConfigUi_cb_tt_IgnoreMateriaForBis {
            get {
                return ResourceManager.GetString("ConfigUi_cb_tt_IgnoreMateriaForBis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Censored.
        /// </summary>
        internal static string ConfigUi_CharNameFormat_a {
            get {
                return ResourceManager.GetString("ConfigUi_CharNameFormat_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initials only.
        /// </summary>
        internal static string ConfigUi_CharNameFormat_i {
            get {
                return ResourceManager.GetString("ConfigUi_CharNameFormat_i", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initials + Server.
        /// </summary>
        internal static string ConfigUi_CharNameFormat_is {
            get {
                return ResourceManager.GetString("ConfigUi_CharNameFormat_is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name only.
        /// </summary>
        internal static string ConfigUi_CharNameFormat_n {
            get {
                return ResourceManager.GetString("ConfigUi_CharNameFormat_n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name + Server.
        /// </summary>
        internal static string ConfigUi_CharNameFormat_ns {
            get {
                return ResourceManager.GetString("ConfigUi_CharNameFormat_ns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configured colors.
        /// </summary>
        internal static string Configui_hdg_Colors {
            get {
                return ResourceManager.GetString("Configui_hdg_Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order in which loot rules should be applied.
        /// </summary>
        internal static string ConfigUi_hdg_LootRuleOrder {
            get {
                return ResourceManager.GetString("ConfigUi_hdg_LootRuleOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority to loot for each role (smaller is higher priority).
        /// </summary>
        internal static string ConfigUi_hdg_RolePriority {
            get {
                return ResourceManager.GetString("ConfigUi_hdg_RolePriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item format.
        /// </summary>
        internal static string Configui_in_ItemFormat {
            get {
                return ResourceManager.GetString("Configui_in_ItemFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens group overview window when you log in.
        /// </summary>
        internal static string Configui_in_tt_OpenOnLogin {
            get {
                return ResourceManager.GetString("Configui_in_tt_OpenOnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        internal static string ConfigUi_tab_Appearance {
            get {
                return ResourceManager.GetString("ConfigUi_tab_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current priority.
        /// </summary>
        internal static string ConfigUi_txt_currentPrio {
            get {
                return ResourceManager.GetString("ConfigUi_txt_currentPrio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available options.
        /// </summary>
        internal static string ConfigUi_txt_ItemFormatAvailable {
            get {
                return ResourceManager.GetString("ConfigUi_txt_ItemFormatAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        internal static string CurrentGear {
            get {
                return ResourceManager.GetString("CurrentGear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select gearset.
        /// </summary>
        internal static string GearSetSearchWindow_button_Select {
            get {
                return ResourceManager.GetString("GearSetSearchWindow_button_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iLvl range:.
        /// </summary>
        internal static string GearSetSearchWindow_iLvlRange {
            get {
                return ResourceManager.GetString("GearSetSearchWindow_iLvlRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Add new.
        /// </summary>
        internal static string GearSetSelect_Add_new {
            get {
                return ResourceManager.GetString("GearSetSelect_Add_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Search known sets.
        /// </summary>
        internal static string GearSetSelect_AddFromDB {
            get {
                return ResourceManager.GetString("GearSetSelect_AddFromDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Gear.
        /// </summary>
        internal static string InventoryUi_hdg_additionalGear {
            get {
                return ResourceManager.GetString("InventoryUi_hdg_additionalGear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s inventory.
        /// </summary>
        internal static string InventoryUi_Title {
            get {
                return ResourceManager.GetString("InventoryUi_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best in Slot.
        /// </summary>
        internal static string ItemTooltip_hdg_bis {
            get {
                return ResourceManager.GetString("ItemTooltip_hdg_bis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipped.
        /// </summary>
        internal static string ItemTooltip_hdg_Equipped {
            get {
                return ResourceManager.GetString("ItemTooltip_hdg_Equipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greed.
        /// </summary>
        internal static string LootCategory_Greed {
            get {
                return ResourceManager.GetString("LootCategory_Greed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need.
        /// </summary>
        internal static string LootCategory_Need {
            get {
                return ResourceManager.GetString("LootCategory_Need", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass.
        /// </summary>
        internal static string LootCategory_Pass {
            get {
                return ResourceManager.GetString("LootCategory_Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undecided.
        /// </summary>
        internal static string LootCategory_Undecided {
            get {
                return ResourceManager.GetString("LootCategory_Undecided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Award to all.
        /// </summary>
        internal static string LootResultWindow_Button_AwardGuaranteed {
            get {
                return ResourceManager.GetString("LootResultWindow:Button:AwardGuaranteed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Award 1 to each player.
        /// </summary>
        internal static string LootResultWindow_Button_AwardGuaranteed_Tooltip {
            get {
                return ResourceManager.GetString("LootResultWindow:Button:AwardGuaranteed:Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BIS &gt; Upgrade.
        /// </summary>
        internal static string LootRule_BISOverUpgrade {
            get {
                return ResourceManager.GetString("LootRule_BISOverUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prioritize by role.
        /// </summary>
        internal static string LootRule_ByRole {
            get {
                return ResourceManager.GetString("LootRule_ByRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can buy.
        /// </summary>
        internal static string LootRule_CanBuy {
            get {
                return ResourceManager.GetString("LootRule_CanBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can use now.
        /// </summary>
        internal static string LootRule_CanUse {
            get {
                return ResourceManager.GetString("LootRule_CanUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loot rule.
        /// </summary>
        internal static string LootRule_DataTypeName {
            get {
                return ResourceManager.GetString("LootRule_DataTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % DPS gained.
        /// </summary>
        internal static string LootRule_DPSGain {
            get {
                return ResourceManager.GetString("LootRule_DPSGain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore.
        /// </summary>
        internal static string LootRule_draw_cb_ignore {
            get {
                return ResourceManager.GetString("LootRule_draw_cb_ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activated.
        /// </summary>
        internal static string LootRule_Draw_cb_tt_active {
            get {
                return ResourceManager.GetString("LootRule_Draw_cb_tt_active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore players/jobs not using this in BiS.
        /// </summary>
        internal static string LootRule_draw_cb_tt_ignore_bis {
            get {
                return ResourceManager.GetString("LootRule_draw_cb_tt_ignore_bis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore players/jobs that could buy these.
        /// </summary>
        internal static string LootRule_draw_cb_tt_ignore_canBuy {
            get {
                return ResourceManager.GetString("LootRule_draw_cb_tt_ignore_canBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore players/jobs not able to use.
        /// </summary>
        internal static string LootRule_draw_cb_tt_ignore_canUse {
            get {
                return ResourceManager.GetString("LootRule_draw_cb_tt_ignore_canUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore players that have no need.
        /// </summary>
        internal static string LootRule_draw_cb_tt_ignore_needGreed {
            get {
                return ResourceManager.GetString("LootRule_draw_cb_tt_ignore_needGreed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greed.
        /// </summary>
        internal static string LootRule_Greed {
            get {
                return ResourceManager.GetString("LootRule_Greed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highest ItemLevel Gain.
        /// </summary>
        internal static string LootRule_HighestItemLevelGain {
            get {
                return ResourceManager.GetString("LootRule_HighestItemLevelGain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lowest overall ItemLevel.
        /// </summary>
        internal static string LootRule_LowestItemLevel {
            get {
                return ResourceManager.GetString("LootRule_LowestItemLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need over Greed.
        /// </summary>
        internal static string LootRule_Need {
            get {
                return ResourceManager.GetString("LootRule_Need", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolling.
        /// </summary>
        internal static string LootRule_Rolling {
            get {
                return ResourceManager.GetString("LootRule_Rolling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results for {0} ({1}).
        /// </summary>
        internal static string LootSession_heading_results {
            get {
                return ResourceManager.GetString("LootSession_heading_results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution started.
        /// </summary>
        internal static string LootSession_State_DISTRIBUTION_STARTED {
            get {
                return ResourceManager.GetString("LootSession_State_DISTRIBUTION_STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        internal static string LootSession_State_FINISHED {
            get {
                return ResourceManager.GetString("LootSession_State_FINISHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loot locked.
        /// </summary>
        internal static string LootSession_State_LOOT_CHOSEN {
            get {
                return ResourceManager.GetString("LootSession_State_LOOT_CHOSEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choosing Loot.
        /// </summary>
        internal static string LootSession_State_STARTED {
            get {
                return ResourceManager.GetString("LootSession_State_STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role priority.
        /// </summary>
        internal static string LootSession_text_rolePriority {
            get {
                return ResourceManager.GetString("LootSession_text_rolePriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes made here only affect this loot session.
        /// </summary>
        internal static string LootSession_text_rolePriorityHint {
            get {
                return ResourceManager.GetString("LootSession_text_rolePriorityHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        internal static string LootSessionUi_btn_Calc {
            get {
                return ResourceManager.GetString("LootSessionUi_btn_Calc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculates results of loot distribution according to the rules and current equipment
        ///            of players
        ///            Locks the loot selection
        ///        .
        /// </summary>
        internal static string LootSessionUi_btn_tt_Calc {
            get {
                return ResourceManager.GetString("LootSessionUi_btn_tt_Calc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override ruling options.
        /// </summary>
        internal static string LootSessionUi_btn_tt_Rules {
            get {
                return ResourceManager.GetString("LootSessionUi_btn_tt_Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pos.
        /// </summary>
        internal static string LootSessionUi_resultTable_Col_Pos {
            get {
                return ResourceManager.GetString("LootSessionUi_resultTable_Col_Pos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loot session for {0}.
        /// </summary>
        internal static string LootSessionUi_Title {
            get {
                return ResourceManager.GetString("LootSessionUi_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current State.
        /// </summary>
        internal static string LootsessionUi_txt_state {
            get {
                return ResourceManager.GetString("LootsessionUi_txt_state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        internal static string LootUi_Results_btn_Abort {
            get {
                return ResourceManager.GetString("LootUi_Results_btn_Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort distribution to change loot or rules.
        /// </summary>
        internal static string LootUi_Results_btn_tt_Abort {
            get {
                return ResourceManager.GetString("LootUi_Results_btn_tt_Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Award to player.
        /// </summary>
        internal static string LootUi_results_btn_tt_Award {
            get {
                return ResourceManager.GetString("LootUi_results_btn_tt_Award", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greed only.
        /// </summary>
        internal static string LootUi_Results_GreedOnly {
            get {
                return ResourceManager.GetString("LootUi_Results_GreedOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guaranteed Items (per player).
        /// </summary>
        internal static string LootUi_Results_hdg_GuaranteedItems {
            get {
                return ResourceManager.GetString("LootUi_Results_hdg_GuaranteedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needed items.
        /// </summary>
        internal static string LootUi_Results_hdg_NeededItems {
            get {
                return ResourceManager.GetString("LootUi_Results_hdg_NeededItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to awarded to.
        /// </summary>
        internal static string LootUi_Results_ItemAwardedTo {
            get {
                return ResourceManager.GetString("LootUi_Results_ItemAwardedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to won.
        /// </summary>
        internal static string LootUi_Results_PlayerWon {
            get {
                return ResourceManager.GetString("LootUi_Results_PlayerWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to over.
        /// </summary>
        internal static string LootUi_Results_PlayerWonOver {
            get {
                return ResourceManager.GetString("LootUi_Results_PlayerWonOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items to distribute.
        /// </summary>
        internal static string LootUi_Results_PossibleItems {
            get {
                return ResourceManager.GetString("LootUi_Results_PossibleItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule.
        /// </summary>
        internal static string LootUI_Results_Rule {
            get {
                return ResourceManager.GetString("LootUI_Results_Rule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick compare.
        /// </summary>
        internal static string PlayerDetail_button_quickCompare {
            get {
                return ResourceManager.GetString("PlayerDetail_button_quickCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Details for {0}.
        /// </summary>
        internal static string PlayerDetailsUi_Title {
            get {
                return ResourceManager.GetString("PlayerDetailsUi_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gain.
        /// </summary>
        internal static string QuickCompare_StatGain {
            get {
                return ResourceManager.GetString("QuickCompare_StatGain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Gear.
        /// </summary>
        internal static string QuickCompareUi_hdg_NewGear {
            get {
                return ResourceManager.GetString("QuickCompareUi_hdg_NewGear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare.
        /// </summary>
        internal static string QuickCompareUi_Title {
            get {
                return ResourceManager.GetString("QuickCompareUi_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Stats.
        /// </summary>
        internal static string StatTable_MainStats_Title {
            get {
                return ResourceManager.GetString("StatTable_MainStats_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary Stats.
        /// </summary>
        internal static string StatTable_SecondaryStats_Title {
            get {
                return ResourceManager.GetString("StatTable_SecondaryStats_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill with target ({0}) data.
        /// </summary>
        internal static string Ui_btn_addPlayerFromTarget_tt {
            get {
                return ResourceManager.GetString("Ui_btn_addPlayerFromTarget_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From current Group.
        /// </summary>
        internal static string Ui_btn_newGroupAutomatic {
            get {
                return ResourceManager.GetString("Ui_btn_newGroupAutomatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From scratch.
        /// </summary>
        internal static string Ui_btn_newGroupManual {
            get {
                return ResourceManager.GetString("Ui_btn_newGroupManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update {0} ({1}) from etro.
        /// </summary>
        internal static string Ui_btn_tt_etroUpdate {
            get {
                return ResourceManager.GetString("Ui_btn_tt_etroUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open inventory window.
        /// </summary>
        internal static string Ui_btn_tt_inventory {
            get {
                return ResourceManager.GetString("Ui_btn_tt_inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show player details for.
        /// </summary>
        internal static string Ui_btn_tt_PlayerDetails {
            get {
                return ResourceManager.GetString("Ui_btn_tt_PlayerDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quickly compare gear.
        /// </summary>
        internal static string Ui_btn_tt_quickCompare {
            get {
                return ResourceManager.GetString("Ui_btn_tt_quickCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Configuration.
        /// </summary>
        internal static string ui_btn_tt_showConfig {
            get {
                return ResourceManager.GetString("ui_btn_tt_showConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update &quot;{0}&quot; from Etro.gg.
        /// </summary>
        internal static string Ui_btn_tt_UpdateFrmEtro {
            get {
                return ResourceManager.GetString("Ui_btn_tt_UpdateFrmEtro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        internal static string Ui_MainTable_Col_Player {
            get {
                return ResourceManager.GetString("Ui_MainTable_Col_Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort.
        /// </summary>
        internal static string Ui_MainTable_Col_Sort {
            get {
                return ResourceManager.GetString("Ui_MainTable_Col_Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Player.
        /// </summary>
        internal static string Ui_text_emptyPlayer {
            get {
                return ResourceManager.GetString("Ui_text_emptyPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribute loot for:.
        /// </summary>
        internal static string Ui_text_openLootSessioon {
            get {
                return ResourceManager.GetString("Ui_text_openLootSessioon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loot Master.
        /// </summary>
        internal static string Ui_Title {
            get {
                return ResourceManager.GetString("Ui_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Dmg with a 100 potency skill adjusted for faster GCDs.
        /// </summary>
        internal static string Ui_tt_Dmgper100 {
            get {
                return ResourceManager.GetString("Ui_tt_Dmgper100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No jobs created.
        /// </summary>
        internal static string Ui_txt_noJobs {
            get {
                return ResourceManager.GetString("Ui_txt_noJobs", resourceCulture);
            }
        }
    }
}
