//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HimbeertoniRaidTool.Plugin.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LootmasterLoc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LootmasterLoc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HimbeertoniRaidTool.Plugin.Localization.LootmasterLoc", typeof(LootmasterLoc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add empty group.
        /// </summary>
        internal static string Add_empty_group {
            get {
                return ResourceManager.GetString("Add empty group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add from DB.
        /// </summary>
        internal static string Add_from_DB {
            get {
                return ResourceManager.GetString("Add from DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Created.
        /// </summary>
        internal static string AutoCreatedGroupName {
            get {
                return ResourceManager.GetString("AutoCreatedGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examples.
        /// </summary>
        internal static string Config_hdg_Examples {
            get {
                return ResourceManager.GetString("Config_hdg_Examples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore Materia.
        /// </summary>
        internal static string Config_input_IgnoreMateriaForBis {
            get {
                return ResourceManager.GetString("Config_input_IgnoreMateriaForBis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open group overview on login.
        /// </summary>
        internal static string Config_input_OpenOnLogin {
            get {
                return ResourceManager.GetString("Config_input_OpenOnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens group overview window when you log in.
        /// </summary>
        internal static string Config_input_OpenOnLogin_tt {
            get {
                return ResourceManager.GetString("Config_input_OpenOnLogin_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color items by item level.
        /// </summary>
        internal static string Config_Lootmaster_ColoredItemNames {
            get {
                return ResourceManager.GetString("Config:Lootmaster:ColoredItemNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configured colors.
        /// </summary>
        internal static string Config_Lootmaster_Colors {
            get {
                return ResourceManager.GetString("Config:Lootmaster:Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show item icon in group overview.
        /// </summary>
        internal static string Config_Lootmaster_IconInGroupOverview {
            get {
                return ResourceManager.GetString("Config:Lootmaster:IconInGroupOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore Materia when determining if an item is equivalent to BiS.
        /// </summary>
        internal static string Config_Lootmaster_IgnoreMateriaForBisTooltip {
            get {
                return ResourceManager.GetString("Config:Lootmaster:IgnoreMateriaForBisTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item format.
        /// </summary>
        internal static string Config_Lootmaster_ItemFormat {
            get {
                return ResourceManager.GetString("Config:Lootmaster:ItemFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available options.
        /// </summary>
        internal static string Config_Lootmaster_ItemFormat_Available {
            get {
                return ResourceManager.GetString("Config:Lootmaster:ItemFormat:Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority to loot for each role (smaller is higher priority).
        /// </summary>
        internal static string ConfigRolePriority {
            get {
                return ResourceManager.GetString("ConfigRolePriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current priority.
        /// </summary>
        internal static string Current_priority {
            get {
                return ResourceManager.GetString("Current priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        internal static string CurrentGear {
            get {
                return ResourceManager.GetString("CurrentGear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete group.
        /// </summary>
        internal static string Delete_group {
            get {
                return ResourceManager.GetString("Delete group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete following group:.
        /// </summary>
        internal static string DeleteRaidGroup {
            get {
                return ResourceManager.GetString("DeleteRaidGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From current Group.
        /// </summary>
        internal static string From_current_Group {
            get {
                return ResourceManager.GetString("From current Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From scratch.
        /// </summary>
        internal static string From_scratch {
            get {
                return ResourceManager.GetString("From scratch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select gearset.
        /// </summary>
        internal static string GearSetSearchWindow_button_Select {
            get {
                return ResourceManager.GetString("GearSetSearchWindow_button_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iLvl range:.
        /// </summary>
        internal static string GearSetSearchWindow_iLvlRange {
            get {
                return ResourceManager.GetString("GearSetSearchWindow_iLvlRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Add new.
        /// </summary>
        internal static string GearSetSelect_Add_new {
            get {
                return ResourceManager.GetString("GearSetSelect_Add_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Search known sets.
        /// </summary>
        internal static string GearSetSelect_AddFromDB {
            get {
                return ResourceManager.GetString("GearSetSelect_AddFromDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right click for more options.
        /// </summary>
        internal static string GroupTabTooltip {
            get {
                return ResourceManager.GetString("GroupTabTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hold shift.
        /// </summary>
        internal static string ImGuiHelper_GuardedButton_notice {
            get {
                return ResourceManager.GetString("ImGuiHelper_GuardedButton_notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Gear.
        /// </summary>
        internal static string InventoryUi_heading_additionalGear {
            get {
                return ResourceManager.GetString("InventoryUi_heading_additionalGear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s inventory.
        /// </summary>
        internal static string InventoryWindow_Title {
            get {
                return ResourceManager.GetString("InventoryWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore players/jobs not using this in BiS.
        /// </summary>
        internal static string loot_rule_ignore_tooltip_bis {
            get {
                return ResourceManager.GetString("loot_rule:ignore:tooltip:bis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore players/jobs that could buy these.
        /// </summary>
        internal static string loot_rule_ignore_tooltip_can_buy {
            get {
                return ResourceManager.GetString("loot_rule:ignore:tooltip:can_buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore players/jobs not able to use.
        /// </summary>
        internal static string loot_rule_ignore_tooltip_can_use {
            get {
                return ResourceManager.GetString("loot_rule:ignore:tooltip:can_use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore players that have no need.
        /// </summary>
        internal static string loot_rule_ignore_tooltip_need_greed {
            get {
                return ResourceManager.GetString("loot_rule:ignore:tooltip:need_greed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greed.
        /// </summary>
        internal static string LootCategory_Greed {
            get {
                return ResourceManager.GetString("LootCategory:Greed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need.
        /// </summary>
        internal static string LootCategory_Need {
            get {
                return ResourceManager.GetString("LootCategory:Need", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass.
        /// </summary>
        internal static string LootCategory_Pass {
            get {
                return ResourceManager.GetString("LootCategory:Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undecided.
        /// </summary>
        internal static string LootCategory_Undecided {
            get {
                return ResourceManager.GetString("LootCategory:Undecided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens LootMaster Window (or /lm as short variant).
        /// </summary>
        internal static string lootmaster {
            get {
                return ResourceManager.GetString("lootmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit gearset: {0}.
        /// </summary>
        internal static string Lootmaster_button_editGear_tooltip {
            get {
                return ResourceManager.GetString("Lootmaster_button_editGear_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update {0} ({1}) from etro.
        /// </summary>
        internal static string Lootmaster_button_etroUpdate_tooltip {
            get {
                return ResourceManager.GetString("Lootmaster_button_etroUpdate_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open inventory window.
        /// </summary>
        internal static string lootmaster_button_inventory_tooltip {
            get {
                return ResourceManager.GetString("lootmaster_button_inventory_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From current Group.
        /// </summary>
        internal static string Lootmaster_button_newGroupAutomatic {
            get {
                return ResourceManager.GetString("Lootmaster_button_newGroupAutomatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From scratch.
        /// </summary>
        internal static string Lootmaster_button_newGRoupManual {
            get {
                return ResourceManager.GetString("Lootmaster_button_newGRoupManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add empty group.
        /// </summary>
        internal static string Lootmaster_button_newGRoupManual_tooltip {
            get {
                return ResourceManager.GetString("Lootmaster_button_newGRoupManual_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quickly compare gear.
        /// </summary>
        internal static string lootmaster_button_quickCompare_tooltip {
            get {
                return ResourceManager.GetString("lootmaster:button:quickCompare:tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Configuration.
        /// </summary>
        internal static string lootmaster_button_showconfig_tooltip {
            get {
                return ResourceManager.GetString("lootmaster:button:showconfig:tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap Position.
        /// </summary>
        internal static string lootmaster_button_swapposition_tooltip {
            get {
                return ResourceManager.GetString("lootmaster:button:swapposition:tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color items according to the item level.
        /// </summary>
        internal static string Lootmaster_ColoredItemNamesTooltip {
            get {
                return ResourceManager.GetString("Lootmaster:ColoredItemNamesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete job (hold Shift).
        /// </summary>
        internal static string lootmaster_detail_deleteJob_tooltip {
            get {
                return ResourceManager.GetString("lootmaster:detail:deleteJob:tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move job down.
        /// </summary>
        internal static string lootmaster_detail_jobDown_tooltip {
            get {
                return ResourceManager.GetString("lootmaster:detail:jobDown:tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move job up.
        /// </summary>
        internal static string lootmaster_detail_jobUp_tooltip {
            get {
                return ResourceManager.GetString("lootmaster:detail:jobUp:tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No jobs created.
        /// </summary>
        internal static string Lootmaster_text_noJobs {
            get {
                return ResourceManager.GetString("Lootmaster_text_noJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove group {0} (hold shift).
        /// </summary>
        internal static string LootmasterUi_button_deleteGRoup_tooltip {
            get {
                return ResourceManager.GetString("LootmasterUi_button_deleteGRoup_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit group {0}.
        /// </summary>
        internal static string LootmasterUi_button_editGroup {
            get {
                return ResourceManager.GetString("LootmasterUi_button_editGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right click for more options.
        /// </summary>
        internal static string LootmasterUi_button_group_tooltip {
            get {
                return ResourceManager.GetString("LootmasterUi_button_group_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Award to player.
        /// </summary>
        internal static string LootResult_AwardButton_Tooltip {
            get {
                return ResourceManager.GetString("LootResult:AwardButton:Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greed only.
        /// </summary>
        internal static string LootResult_GreedOnly {
            get {
                return ResourceManager.GetString("LootResult:GreedOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to awarded to.
        /// </summary>
        internal static string LootResult_ItemAwardedTo {
            get {
                return ResourceManager.GetString("LootResult:ItemAwardedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to won.
        /// </summary>
        internal static string LootResult_PlayerWon {
            get {
                return ResourceManager.GetString("LootResult:PlayerWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to over.
        /// </summary>
        internal static string LootResult_PlayerWonOver {
            get {
                return ResourceManager.GetString("LootResult:PlayerWonOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items to distribute.
        /// </summary>
        internal static string LootResult_PossibleItems {
            get {
                return ResourceManager.GetString("LootResult:PossibleItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        internal static string LootResults_AbortButton_Text {
            get {
                return ResourceManager.GetString("LootResults:AbortButton:Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort distribution to change loot or rules.
        /// </summary>
        internal static string LootResults_AbortButton_Tooltip {
            get {
                return ResourceManager.GetString("LootResults:AbortButton:Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Award to all.
        /// </summary>
        internal static string LootResultWindow_Button_AwardGuaranteed {
            get {
                return ResourceManager.GetString("LootResultWindow:Button:AwardGuaranteed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Award 1 to each player.
        /// </summary>
        internal static string LootResultWindow_Button_AwardGuaranteed_Tooltip {
            get {
                return ResourceManager.GetString("LootResultWindow:Button:AwardGuaranteed:Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guaranteed Items (per player).
        /// </summary>
        internal static string LootResultWindow_GuaranteedItems {
            get {
                return ResourceManager.GetString("LootResultWindow:GuaranteedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BIS &gt; Upgrade.
        /// </summary>
        internal static string LootRule_BISOverUpgrade {
            get {
                return ResourceManager.GetString("LootRule_BISOverUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prioritize by role.
        /// </summary>
        internal static string LootRule_ByRole {
            get {
                return ResourceManager.GetString("LootRule_ByRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can buy.
        /// </summary>
        internal static string LootRule_CanBuy {
            get {
                return ResourceManager.GetString("LootRule:CanBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can use now.
        /// </summary>
        internal static string LootRule_CanUse {
            get {
                return ResourceManager.GetString("LootRule:CanUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % DPS gained.
        /// </summary>
        internal static string LootRule_DPSGain {
            get {
                return ResourceManager.GetString("LootRule_DPSGain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greed.
        /// </summary>
        internal static string LootRule_Greed {
            get {
                return ResourceManager.GetString("LootRule_Greed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highest ItemLevel Gain.
        /// </summary>
        internal static string LootRule_HighestItemLevelGain {
            get {
                return ResourceManager.GetString("LootRule_HighestItemLevelGain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lowest overall ItemLevel.
        /// </summary>
        internal static string LootRule_LowestItemLevel {
            get {
                return ResourceManager.GetString("LootRule_LowestItemLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need over Greed.
        /// </summary>
        internal static string LootRule_Need {
            get {
                return ResourceManager.GetString("LootRule_Need", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolling.
        /// </summary>
        internal static string LootRule_Rolling {
            get {
                return ResourceManager.GetString("LootRule_Rolling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order in which loot rules should be applied.
        /// </summary>
        internal static string LootRuleOrder {
            get {
                return ResourceManager.GetString("LootRuleOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        internal static string LootSession_CalcButton_Text {
            get {
                return ResourceManager.GetString("LootSession:CalcButton:Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculates results of loot distribution according to the rules and current equipment
        ///            of players
        ///            Locks the loot selection
        ///        .
        /// </summary>
        internal static string LootSession_CalcButton_Tooltip {
            get {
                return ResourceManager.GetString("LootSession:CalcButton:Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results for {0} ({1}).
        /// </summary>
        internal static string LootSession_heading_results {
            get {
                return ResourceManager.GetString("LootSession_heading_results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override ruling options.
        /// </summary>
        internal static string LootSession_RulesButton_Tooltip {
            get {
                return ResourceManager.GetString("LootSession:RulesButton:Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current State.
        /// </summary>
        internal static string Lootsession_State {
            get {
                return ResourceManager.GetString("Lootsession:State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution started.
        /// </summary>
        internal static string LootSession_State_DISTRIBUTION_STARTED {
            get {
                return ResourceManager.GetString("LootSession:State:DISTRIBUTION_STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        internal static string LootSession_State_FINISHED {
            get {
                return ResourceManager.GetString("LootSession:State:FINISHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loot locked.
        /// </summary>
        internal static string LootSession_State_LOOT_CHOSEN {
            get {
                return ResourceManager.GetString("LootSession:State:LOOT_CHOSEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choosing Loot.
        /// </summary>
        internal static string LootSession_State_STARTED {
            get {
                return ResourceManager.GetString("LootSession:State:STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role priority.
        /// </summary>
        internal static string LootSession_text_rolePriority {
            get {
                return ResourceManager.GetString("LootSession_text_rolePriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes made here only affect this loot session.
        /// </summary>
        internal static string LootSession_text_rolePriorityHint {
            get {
                return ResourceManager.GetString("LootSession_text_rolePriorityHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loot session for {0}.
        /// </summary>
        internal static string LootSessionWindow_Title {
            get {
                return ResourceManager.GetString("LootSessionWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick compare.
        /// </summary>
        internal static string PlayerDetail_button_quickCompare {
            get {
                return ResourceManager.GetString("PlayerDetail_button_quickCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit {0} gear.
        /// </summary>
        internal static string PlayerDetail_buttton_editGear_tooltip {
            get {
                return ResourceManager.GetString("PlayerDetail_buttton_editGear_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Gear.
        /// </summary>
        internal static string QuickCompare_NewGear {
            get {
                return ResourceManager.GetString("QuickCompare_NewGear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gain.
        /// </summary>
        internal static string QuickCompare_StatGain {
            get {
                return ResourceManager.GetString("QuickCompare_StatGain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare.
        /// </summary>
        internal static string QuickCompareWindow_Title {
            get {
                return ResourceManager.GetString("QuickCompareWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Stats.
        /// </summary>
        internal static string StatTable_MainStats_Title {
            get {
                return ResourceManager.GetString("StatTable_MainStats_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary Stats.
        /// </summary>
        internal static string StatTable_SecondaryStats_Title {
            get {
                return ResourceManager.GetString("StatTable_SecondaryStats_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill with target ({0}).
        /// </summary>
        internal static string Ui_btn_addPlayerFromTarget_tt {
            get {
                return ResourceManager.GetString("Ui_btn_addPlayerFromTarget_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove {0} from this group (hold shift).
        /// </summary>
        internal static string Ui_btn_removePlayer_tt {
            get {
                return ResourceManager.GetString("Ui_btn_removePlayer_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add character from DB.
        /// </summary>
        internal static string Ui_button_addCharFromDb_tt {
            get {
                return ResourceManager.GetString("Ui_button_addCharFromDb_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add empty.
        /// </summary>
        internal static string Ui_button_addEmptyPlayer_tt {
            get {
                return ResourceManager.GetString("Ui_button_addEmptyPlayer_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add player from DB.
        /// </summary>
        internal static string Ui_button_addExistinPlayer_tt {
            get {
                return ResourceManager.GetString("Ui_button_addExistinPlayer_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activated.
        /// </summary>
        internal static string ui_loot_rule_active_tooltip {
            get {
                return ResourceManager.GetString("ui:loot_rule:active:tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore.
        /// </summary>
        internal static string ui_loot_rule_ignore {
            get {
                return ResourceManager.GetString("ui:loot_rule:ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        internal static string Ui_MainTable_Col_Player {
            get {
                return ResourceManager.GetString("Ui_MainTable_Col_Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort.
        /// </summary>
        internal static string Ui_MainTable_Col_Sort {
            get {
                return ResourceManager.GetString("Ui_MainTable_Col_Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Player.
        /// </summary>
        internal static string Ui_text_emptyPlayer {
            get {
                return ResourceManager.GetString("Ui_text_emptyPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribute loot for:.
        /// </summary>
        internal static string Ui_text_openLootSessioon {
            get {
                return ResourceManager.GetString("Ui_text_openLootSessioon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loot Master.
        /// </summary>
        internal static string Ui_Title {
            get {
                return ResourceManager.GetString("Ui_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update &quot;{0}&quot; from Etro.gg.
        /// </summary>
        internal static string UpdateBis {
            get {
                return ResourceManager.GetString("UpdateBis", resourceCulture);
            }
        }
    }
}
